### ISSUE TITLE
TODO List ❗

### ISSUE THREAD

**Issue by shawkyelshazly1** [shawkyelshazly1/Pomodoro-App#1]
### Features:

- [x] DB FUnctionality with JSON object written on .txt file saved locally
- [x] Showing tasks list on-screen with ability to add & remove tasks
- [ ] Functionality to start specific tasks and pause it with state saved while app is runnig

**Comment by shawkyelshazly1** [comment]
Fixed starting and stopping specific task with adjusting pomodoros counter to the assigned task or infinite
